[package]
name = "heptabao-runtime-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
sha2 = "=0.10.9"
zeroize = "=1.8.1"
heptabao-durable-service = { path = "../heptabao-durable-service" }

[lib]
path = "src/lib.rs"

[lints]
workspace = true
