//! Snapshot isolation and fixed pre-COW storage representations.
use super::*;

type TestResult<T = ()> = std::result::Result<T, Box<dyn std::error::Error>>;

// Literal old serde representations, not values generated by the new wrapper.
const LEGACY_KV1: &[u8] = br#"{"revision":1,"incarnation":1,"description":"legacy","backend":{"Kv1":{"a":{"secret":"old"},"b":{"secret":"other"}}}}"#;
const LEGACY_KV2: &[u8] = br#"{"revision":1,"incarnation":1,"description":"legacy","backend":{"Kv2":{"config":{"max_versions":0,"cas_required":false,"delete_version_after":0},"entries":{"a":{"config":{"max_versions":0,"cas_required":false,"delete_version_after":0},"current_version":1,"oldest_version":0,"created_at":10,"updated_at":10,"custom_metadata":null,"versions":{"1":{"created_at":10,"deletion_at":null,"destroyed":false,"data":{"secret":"old"}}}}}}}}"#;

fn call(
    state: &mut EngineState,
    method: &str,
    path: &str,
    body: Value,
) -> TestResult<EngineResponse> {
    state
        .handle("", method, path, &body, 100)?
        .ok_or_else(|| "missing engine response".into())
}

fn mount<'a>(state: &'a EngineState, name: &str) -> TestResult<&'a Mount> {
    state
        .namespaces
        .get("")
        .and_then(|ns| ns.mounts.get(name))
        .ok_or_else(|| "missing mount".into())
}

#[test]
fn fixed_legacy_mounts_and_payloads_keep_identical_serialized_bytes() -> TestResult {
    for bytes in [LEGACY_KV1, LEGACY_KV2] {
        let decoded: Mount = serde_json::from_slice(bytes)?;
        assert_eq!(serde_json::to_vec(&decoded)?, bytes);
        let namespace = NamespaceState {
            mounts: BTreeMap::from([("legacy/".into(), decoded)]),
            mount_epochs: BTreeMap::new(),
            identity: identity::IdentityState::default(),
        };
        let mut state = EngineState {
            records: None,
            lease_clock: 0,
            namespaces: BTreeMap::from([("".into(), CowNamespace(Arc::new(namespace)))]),
            workflow: crate::service_workflow::WorkflowState::default(),
        };
        let path = if bytes == LEGACY_KV1 {
            "legacy/a"
        } else {
            "legacy/data/a"
        };
        let response = call(&mut state, "GET", path, json!({}))?;
        let data = if bytes == LEGACY_KV1 {
            &response.body["data"]
        } else {
            &response.body["data"]["data"]
        };
        assert_eq!(data, &json!({"secret":"old"}));
        assert_eq!(serde_json::to_vec(mount(&state, "legacy/")?)?, bytes);
    }
    Ok(())
}

#[test]
fn small_kv1_write_shares_unrelated_mount_and_payload_but_preserves_old_snapshot() -> TestResult {
    let mut state = EngineState::default();
    for name in ["active", "cold"] {
        assert_eq!(
            call(
                &mut state,
                "POST",
                &format!("sys/mounts/{name}"),
                json!({"type":"kv","options":{"version":"1"}})
            )?
            .status,
            204
        );
        assert_eq!(
            call(
                &mut state,
                "POST",
                &format!("{name}/large"),
                json!({"payload":"x".repeat(224 * 1024)})
            )?
            .status,
            204
        );
    }
    call(
        &mut state,
        "POST",
        "active/small",
        json!({"value":"before"}),
    )?;
    let snapshot = state.clone();
    let snapshot_bytes = serde_json::to_vec(&snapshot)?;
    assert!(Arc::ptr_eq(
        &mount(&state, "active/")?.0,
        &mount(&snapshot, "active/")?.0
    ));
    call(&mut state, "POST", "active/small", json!({"value":"after"}))?;
    assert!(!Arc::ptr_eq(
        &mount(&state, "active/")?.0,
        &mount(&snapshot, "active/")?.0
    ));
    assert!(Arc::ptr_eq(
        &mount(&state, "cold/")?.0,
        &mount(&snapshot, "cold/")?.0
    ));
    let Backend::Kv1(next) = &mount(&state, "active/")?.backend else {
        return Err("expected KV1".into());
    };
    let Backend::Kv1(old) = &mount(&snapshot, "active/")?.backend else {
        return Err("expected KV1".into());
    };
    assert!(Arc::ptr_eq(
        &next.get("large").ok_or("large missing")?.0,
        &old.get("large").ok_or("large missing")?.0
    ));
    assert_eq!(serde_json::to_vec(&snapshot)?, snapshot_bytes);
    assert_eq!(
        kv::read_v1(old, "GET", "small", &json!({}))?.body["data"],
        json!({"value":"before"})
    );
    call(&mut state, "DELETE", "active/large", json!({}))?;
    assert_eq!(
        call(&mut state, "LIST", "active/", json!({}))?.body["data"]["keys"],
        json!(["small"])
    );
    assert_eq!(
        kv::read_v1(old, "GET", "large", &json!({}))?.body["data"]["payload"],
        "x".repeat(224 * 1024)
    );
    drop(state);
    assert_eq!(serde_json::to_vec(&snapshot)?, snapshot_bytes);
    Ok(())
}

#[test]
fn failed_kv_dispatch_preserves_mount_identity_and_snapshot_contents() -> TestResult {
    let mut state = EngineState::default();
    call(
        &mut state,
        "POST",
        "secret/data/item",
        json!({"data":{"value":"before"}}),
    )?;
    let snapshot = state.clone();
    let before = serde_json::to_vec(&state)?;
    let error = state
        .handle(
            "",
            "POST",
            "secret/data/item",
            &json!({"data":{"value":"forbidden"},"options":{"cas":0}}),
            101,
        )
        .err()
        .ok_or("CAS mismatch accepted")?;
    assert_eq!(error.status, 400);
    assert!(Arc::ptr_eq(
        &mount(&state, "secret/")?.0,
        &mount(&snapshot, "secret/")?.0
    ));
    assert_eq!(serde_json::to_vec(&state)?, before);
    assert_eq!(serde_json::to_vec(&snapshot)?, before);
    Ok(())
}

#[test]
fn mount_configuration_and_removal_are_isolated_from_retained_snapshot() -> TestResult {
    let mut state = EngineState::default();
    call(
        &mut state,
        "POST",
        "secret/data/item",
        json!({"data":{"value":"before"}}),
    )?;
    let snapshot = state.clone();
    let old_bytes = serde_json::to_vec(&snapshot)?;
    call(
        &mut state,
        "POST",
        "sys/mounts/secret/tune",
        json!({"description":"changed"}),
    )?;
    assert_eq!(mount(&state, "secret/")?.description, "changed");
    assert_ne!(
        mount(&state, "secret/")?.revision,
        mount(&snapshot, "secret/")?.revision
    );
    assert!(Arc::ptr_eq(
        &mount(&state, "transit/")?.0,
        &mount(&snapshot, "transit/")?.0
    ));
    call(&mut state, "DELETE", "sys/mounts/secret", json!({}))?;
    assert!(mount(&state, "secret/").is_err());
    assert_eq!(serde_json::to_vec(&snapshot)?, old_bytes);
    Ok(())
}
