[package]
name = "heptabao-single-node-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
heptabao-filesystem-guard = { path = "../heptabao-filesystem-guard" }
heptabao-storage-api = { path = "../heptabao-storage-api" }

[lints]
workspace = true
