[package]
name = "heptabao-p0-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
heptabao-protocol = { path = "../heptabao-protocol" }

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "heptabao-p0-server"
path = "src/main.rs"

[lints]
workspace = true
