#!/usr/bin/env python3
"""Render V1.4.7 using the frozen generator with corrected shell escaping.

The original generator is kept byte-for-byte for a reviewable, narrow repair.
No workflow, test, authority claim or generated input is read back as its own
expected value. Check mode remains read-only and compares complete output bytes.
"""
from __future__ import annotations

import hashlib
from pathlib import Path
from types import ModuleType
from typing import Any

BASELINE_PATH = Path(__file__).with_name("_render_plan_v1_4_7_baseline.py")
BASELINE_SHA256 = "ed72827409aac7da450dce4100365c49bb8ea3a2210fe0767030e2c5c9824aed"


def _load_frozen_renderer() -> ModuleType:
    # Verify and execute the SAME snapshot. A file loader may reopen the path or
    # accept an mtime/size-valid .pyc whose code was not covered by this digest.
    source = BASELINE_PATH.read_bytes()
    if hashlib.sha256(source).hexdigest() != BASELINE_SHA256:
        raise ValueError("frozen V1.4.7 generator integrity mismatch")
    module = ModuleType("heptabao_v147_frozen_renderer")
    module.__file__ = str(BASELINE_PATH)
    module.__package__ = ""
    code = compile(source, str(BASELINE_PATH), "exec", dont_inherit=True)
    exec(code, module.__dict__)
    return module


BASELINE = _load_frozen_renderer()
_ORIGINAL_WORKFLOW = BASELINE.workflow_source
_ORIGINAL_PATHS = BASELINE.normative_paths
_ORIGINAL_STATIC_FILES = BASELINE.static_files


def workflow_source() -> str:
    source = _ORIGINAL_WORKFLOW()
    replacements = (
        ("printf 'source_kind=%s\nsource_sha=%s\ntree=%s\n'",
         r"printf 'source_kind=%s\nsource_sha=%s\ntree=%s\n'"),
        ('compatibility_claim: true"             planning/',
         'compatibility_claim: true" ' + "\\" + "\n" + "            planning/"),
    )
    for before, after in replacements:
        if source.count(before) != 1:
            raise ValueError("frozen workflow escape anchor mismatch")
        source = source.replace(before, after, 1)
    return source


def readme_source() -> str:
    """Build this tranche's entry page from the canonical portal and status.

    Never use the checked-in README as its own expected value. Inherited plans
    remain explicitly historical, and source availability is not qualification.
    """
    status = BASELINE.status_document()
    portal = BASELINE.current_documentation()
    heading = "## Current normative set\n"
    end = "\n## Inherited immutable set\n"
    if portal.count(heading) != 1 or portal.count(end) != 1:
        raise ValueError("current documentation section mismatch")
    table = portal.split(heading, 1)[1].split(end, 1)[0].strip()
    return f'''# HeptaBao

HeptaBao is an independent clean-room Rust reimplementation program for an OpenBao-compatible secrets-management server.

<!-- Generated by scripts/render_plan_v1_4_7.py; update the generator, not this file. -->

## Current truth

- Current plan: **V{status["revision"]} post-merge truth and external admission** for this source tree.
- Plan identity: `{status["plan_id"]}`.
- Candidate state: **{status["status"]}**; this is not a merged or qualified release.
- Current Cargo workspace documentation: **19 / 19** existing crates have developer guides under `docs/modules/`. This is file coverage, not full product design or implementation completion.
- Qualification: **false**.
- Compatibility claim: **false**.
- Dependency selections: **none with production authority**.
- Production, migration, release and mixed-cluster authority: **false**.
- Supported production versions: **none**.

The repository is **not production-deployable**. Do not use it to protect real secrets and do not place real tokens, unseal shares, recovery keys, private keys or production snapshots in source, tests or CI.

## Current normative entry points

`docs/CURRENT_DOCUMENTATION.md` is the canonical current-entry portal. The complete table below is generated from that same portal, not maintained independently.

{table}

## Inherited foundations

- The inherited kernel baseline is **V1.4.6 authoritative recovery closure**, commit `{status["source_baseline"]["commit"]}`, tree `{status["source_baseline"]["tree"]}`.
- **V1.4.5 security invariant closure** and **V1.4.4 module documentation closure** remain inherited regression subjects, not the current plan.
- V1.4.4's file-coverage registry remains `planning/HEPTABAO_MODULE_DOCUMENTATION_COVERAGE_V1_4_4.yaml`; the current module standard and exact-source facts are in the current table above.
- The portal's inherited table retains the older plans, status documents, blocker registers, recovery protocol and validation gates. Historical receipts are not reissued by updating this entry page.

## Architecture boundary

This source tree contains safety-oriented kernel components and a loopback-only P0 memory server. A production composition root, policy, identity, token, lease, namespace, plugin host, secrets engines, Raft/HA, CLI, Agent, Proxy and full OpenBao compatibility remain future product work for this tree. Target-architecture documents and unsubmitted candidates do not imply that these modules exist here.

## Recovery safety boundary

Recovery target admission is atomic through `stage_if_empty`, and target publication executes while the rollback provider holds the exact-current checkpoint fence. Fence outcomes are phase-aware:

- `CheckpointNotCurrent` and `ProviderBeforeEntry` prove the publication closure was not entered;
- `OutcomeUnknownAfterEntry` means the closure ran but clean fence completion cannot be proved;
- `AnchorFenceOutcomeUnknown` requires authoritative readback of both the external anchor and target before any retry.

A successful inner target receipt does not override outer post-entry fence uncertainty. No provider, operator or caller may relabel that state as a safe stale-checkpoint failure.

## Evidence and authority boundary

Technical source, tests, CI, qualification, compatibility and operational authority are distinct. Repository-controlled gates cannot manufacture external repository controls, independently accountable reviews, legal disposition, incident operation, isolated signing, restricted Oracle transfer, power-cut/filesystem laboratory evidence or independent reproduction. Those blockers close only through their declared real completion objects.

`HB-BLK-CTRL-001` and `HB-BLK-EXT-001` through `HB-BLK-EXT-007` remain open. `UNEXECUTED` templates, queued checks, skipped relay workflows and local test logs are not independent completion receipts. This generated entry page changes none of those states.

## Development

Use the declared toolchain and dependency versions. Read and update the guide for each crate changed. Run the current gate first, followed by the inherited regression gates:

```text
python -m pip install --requirement requirements-plan.txt
python scripts/render_plan_v1_4_7.py --check
python scripts/validate_plan_v1_4_7.py
python -m unittest discover -s tests/plan -p 'test_*v1_4_7.py' -v
python -m unittest discover -s tests/plan -p 'test_external_completion_evidence_v1.py' -v
python scripts/validate_plan_v1_4_6.py
python -m unittest discover -s tests/plan -p 'test_plan_v1_4_6.py' -v
python scripts/validate_plan_v1_4_5.py
python -m unittest discover -s tests/plan -p 'test_plan_v1_4_5.py' -v
python scripts/validate_module_documentation_v1_4_4.py
python -m unittest discover -s tests/plan -p 'test_module_documentation_v1_4_4.py' -v
python -m unittest discover -s tests/platform -p 'test_*.py' -v
python -m unittest discover -s tests/oracle -p 'test_*.py' -v
cargo +1.98.0 fmt --all -- --check
cargo +1.98.0 test --locked --workspace --all-targets
cargo +1.98.0 clippy --locked --workspace --all-targets -- -D warnings
```

The README and its regression suite are included in the current normative manifest. Check mode rejects a missing or modified generated README without rewriting it, even when its manifest hash is updated. Exact current-head and prospective-merge identities come from the active pull request and its read-only workflows, not from this README. A source change requires new CI and eligible review; prior-head results are not inherited as approvals.
'''


def static_files() -> dict[Path, str]:
    values = _ORIGINAL_STATIC_FILES()
    values[Path("README.md")] = readme_source()
    return values


def normative_paths(truth: dict[str, Any]) -> list[Path]:
    additions = {
        Path("README.md"),
        Path("tests/plan/test_current_entry_v1_4_7.py"),
        Path("scripts/_render_plan_v1_4_7_baseline.py"),
        Path("tests/plan/test_workflow_render_v1_4_7.py"),
    }
    return sorted(set(_ORIGINAL_PATHS(truth)) | additions, key=lambda path: path.as_posix())


BASELINE.workflow_source = workflow_source
BASELINE.normative_paths = normative_paths
BASELINE.static_files = static_files


def __getattr__(name: str) -> Any:
    # Preserve the generator's public inspection API used by existing tests.
    return getattr(BASELINE, name)


if __name__ == "__main__":
    raise SystemExit(BASELINE.main())
