#!/usr/bin/env python3
"""Compare bounded live Identity authorization on fresh local TLS servers only.

All credentials are generated by the isolated fixtures. No external endpoint,
real token or production-state argument is accepted. Passing this selected
profile is not full Identity/OpenBao compatibility or independent admission.
"""
from __future__ import annotations

from pathlib import Path
from bao_http import Client
from core_isolation import ScenarioFailure
import core_isolation


def run_scenarios(client: Client, results: list[dict] | None = None) -> list[dict]:
    results = [] if results is None else results

    def call(method, path, body=None, token=None):
        return client.request(method, "/v1/" + path, body, token=token)

    def check(name, response, status):
        result = {"case": name, "status": response.status, "passed": response.status == status}
        results.append(result)
        if not result["passed"]:
            raise ScenarioFailure(name)
        return response.body

    def truth(name, condition):
        results.append({"case": name, "passed": bool(condition)})
        if not condition:
            raise ScenarioFailure(name)

    mount = "identity-compare"
    item = mount + "/data/item"
    auth_mount = "identity-login"
    role = "auth/" + auth_mount + "/role/synthetic"
    login_path = "auth/" + auth_mount + "/login"
    check("identity.mount_kv", call("POST", "sys/mounts/" + mount,
          {"type": "kv", "options": {"version": "2"}}), 204)
    check("identity.seed_kv", call("POST", item, {"data": {"v": "synthetic-only"}}), 200)
    rules = f'path "{item}" {{ capabilities = ["read"] }}'
    check("identity.reader_policy", call("PUT", "sys/policies/acl/identity-reader", {"policy": rules}), 204)
    check("identity.creator_policy", call("PUT", "sys/policies/acl/identity-creator", {
        "policy": 'path "auth/token/create" { capabilities = ["update"] }'}), 204)
    check("identity.deny_policy", call("PUT", "sys/policies/acl/identity-deny", {
        "policy": f'path "{item}" {{ capabilities = ["deny"] }}'}), 204)
    check("identity.mount_auth", call("POST", "sys/auth/" + auth_mount, {"type": "approle"}), 204)
    registry = check("identity.read_mount", call("GET", "sys/auth"), 200)
    accessor = registry["data"][auth_mount + "/"]["accessor"]
    truth("identity.accessor_nonempty", isinstance(accessor, str) and bool(accessor))
    check("identity.create_role", call("POST", role, {
        "token_policies": ["default", "identity-creator"], "secret_id_num_uses": 0}), 204)
    role_id = check("identity.role_id", call("GET", role + "/role-id"), 200)["data"]["role_id"]
    secret_id = check("identity.secret_id", call("POST", role + "/secret-id", {}), 200)["data"]["secret_id"]
    credentials = {"role_id": role_id, "secret_id": secret_id}
    logged = check("identity.login", call("POST", login_path, credentials), 200)["auth"]
    token, entity = logged["client_token"], logged["entity_id"]
    truth("identity.entity_nonempty", isinstance(entity, str) and bool(entity))
    entity_path = "identity/entity/id/" + entity
    again = check("identity.repeat_login", call("POST", login_path, credentials), 200)["auth"]
    truth("identity.stable_alias_entity", again["entity_id"] == entity)
    looked = check("identity.alias_lookup", call("POST", "identity/lookup/entity", {
        "alias_name": role_id, "alias_mount_accessor": accessor}), 200)
    truth("identity.alias_binding", looked["data"]["id"] == entity)
    check("identity.initial_read_denied", call("GET", item, token=token), 403)
    check("identity.assign_entity_policy", call("POST", entity_path, {
        "policies": ["identity-reader"], "metadata": {"retained": "synthetic"}}), 204)
    content = check("identity.existing_token_grant", call("GET", item, token=token), 200)
    truth("identity.only_expected_value", content["data"]["data"] == {"v": "synthetic-only"})
    lookup = check("identity.token_policy_projection", call("GET", "auth/token/lookup-self", token=token), 200)
    truth("identity.live_policy_reported", "identity-reader" in lookup["data"].get("identity_policies", []))
    relog = check("identity.login_projection", call("POST", login_path, credentials), 200)["auth"]
    truth("identity.token_and_identity_policies_separate",
          "identity-reader" in relog.get("identity_policies", [])
          and "identity-reader" not in relog.get("token_policies", [])
          and "identity-reader" in relog.get("policies", []))
    child = check("identity.child_issue", call("POST", "auth/token/create", {"ttl": "1h"}, token), 200)["auth"]
    truth("identity.child_binding", child.get("entity_id") == entity)
    truth("identity.child_no_frozen_grant", "identity-reader" not in child.get("token_policies", []))
    child_token = child["client_token"]
    check("identity.child_reads", call("GET", item, token=child_token), 200)
    check("identity.disable", call("POST", entity_path, {"disabled": True}), 204)
    entity_data = check("identity.partial_update_readback", call("GET", entity_path), 200)["data"]
    truth("identity.partial_update_preserves_fields", entity_data.get("metadata") == {"retained": "synthetic"}
          and "identity-reader" in entity_data.get("policies", []))
    check("identity.disabled_existing_token", call("GET", item, token=token), 403)
    check("identity.disabled_child_token", call("GET", item, token=child_token), 403)
    check("identity.disabled_login", call("POST", login_path, credentials), 403)
    check("identity.reenable", call("POST", entity_path, {"disabled": False}), 204)
    check("identity.reenable_does_not_require_new_token", call("GET", item, token=token), 200)
    check("identity.remove_entity_policy", call("POST", entity_path, {"policies": []}), 204)
    check("identity.parent_grant_removed", call("GET", item, token=token), 403)
    check("identity.child_grant_removed", call("GET", item, token=child_token), 403)
    group = check("identity.internal_group", call("POST", "identity/group", {
        "name": "identity-direct", "type": "internal", "policies": [], "member_entity_ids": [entity]}), 200)["data"]["id"]
    parent = check("identity.parent_group", call("POST", "identity/group", {
        "name": "identity-parent", "type": "internal", "policies": ["identity-reader"], "member_group_ids": [group]}), 200)["data"]["id"]
    check("identity.nested_group_grant", call("GET", item, token=token), 200)
    check("identity.rename_parent", call("POST", "identity/group/id/" + parent, {"name": "identity-parent-renamed"}), 204)
    check("identity.group_partial_update_preserves_grant", call("GET", item, token=token), 200)
    check("identity.live_deny", call("POST", "identity/group/id/" + parent,
          {"policies": ["identity-reader", "identity-deny"]}), 204)
    check("identity.deny_dominates", call("GET", item, token=token), 403)
    check("identity.remove_deny", call("POST", "identity/group/id/" + parent,
          {"policies": ["identity-reader"]}), 204)
    check("identity.remove_direct_membership", call("POST", "identity/group/id/" + group,
          {"member_entity_ids": []}), 204)
    check("identity.membership_revokes_existing_token", call("GET", item, token=token), 403)
    check("identity.restore_entity_policy", call("POST", entity_path, {"policies": ["identity-reader"]}), 204)
    check("identity.policy_definition_change", call("PUT", "sys/policies/acl/identity-reader", {
        "policy": f'path "{item}" {{ capabilities = ["deny"] }}'}), 204)
    check("identity.definition_change_revokes", call("GET", item, token=token), 403)
    check("identity.restore_definition", call("PUT", "sys/policies/acl/identity-reader", {"policy": rules}), 204)
    check("identity.restored_read", call("GET", item, token=token), 200)
    check("identity.delete_entity", call("DELETE", entity_path), 204)
    check("identity.deleted_entity_denies", call("GET", item, token=token), 403)
    return results


def main() -> int:
    return core_isolation.main(
        scenario_runner=run_scenarios, profile="identity-live",
        scope="selected_login_entity_and_internal_group_authorization_only",
        runner_path=Path(__file__),
    )


if __name__ == "__main__":
    raise SystemExit(main())
