#!/usr/bin/env python3
"""Real schema30 Kubernetes state -> CIDR role/snapshots -> refused downgrade.

A synthetic HTTPS TokenReview server verifies requests; it is not a kube-apiserver.
Old state is generated by the pinned process, never by editing application bytes.
"""
from __future__ import annotations
import json
from pathlib import Path
import re
import shutil
import tempfile

from bao_http import SafeArgumentParser, private_write
from core_isolation import ROOT, ScenarioFailure, file_hash
from identity_upgrade import validate_binary_pins
from kubernetes_renewal_live import Reviewer, assertion
from online_evidence import admit_output, source_identity
from provider_renewal_upgrade import durable_manifest
from radius_cidrs_live import SourceClient
from radius_renewal_live import renewal_token_shape
from remote_jwks_live import Instance, signing_key

# Actual schema30 build admitted through the committed clean differential receipt.
LEGACY_SOURCE = "6de8ab26c92e6218218efebe7fe15a5f736cb8f1"
LEGACY_HARNESS = LEGACY_SOURCE
LEGACY_SHA256 = "d69b5988c31d85d1b7c453f4ceae1d23cd2cec27102cf0630f5c540a325cc1dc"
LEGACY_RECEIPT = ROOT / "qa/openbao-acceptance/evidence/jwt-bound-claims-6de8ab2.json"
BASE = 'auth/kubernetes-cidr-upgrade'
VALUE_PATH = 'secret/data/kubernetes-cidr-upgrade'
PREFIX = 'kubernetes_cidrs_upgrade.'


def admit_legacy_receipt(expected, receipt):
    if (not isinstance(LEGACY_RECEIPT, Path)
            or re.fullmatch(r'[0-9a-f]{40}', LEGACY_SOURCE or '') is None
            or re.fullmatch(r'[0-9a-f]{40}', LEGACY_HARNESS or '') is None
            or re.fullmatch(r'[0-9a-f]{64}', LEGACY_SHA256 or '') is None):
        raise ValueError('legacy_schema30_receipt_not_yet_pinned')
    identity = receipt.get('candidate_source', {})
    if (expected != LEGACY_SHA256 or receipt.get('status') != 'passed'
            or receipt.get('build_source_commit') != LEGACY_SOURCE
            or receipt.get('source_and_binary_unchanged') is not True
            or receipt.get('runner_unchanged') is not True or receipt.get('cases_match') is not True
            or identity.get('source_commit') != LEGACY_HARNESS
            or identity.get('source_dirty') is not False or identity.get('binary_sha256') != LEGACY_SHA256):
        raise ValueError('legacy_schema30_receipt_mismatch')


def old_role():
    # Fixed historical shape: future helpers cannot inject CIDR fields here.
    return {'bound_service_account_names': ['worker'], 'bound_service_account_namespaces': ['workload'],
            'audience': 'heptabao-online', 'token_policies': ['default', 'upgrade-child'],
            'token_ttl': 600, 'token_max_ttl': 1200}


def old_configuration(reviewer, ca):
    return {'kubernetes_host': reviewer.origin, 'kubernetes_ca_cert': ca,
            'token_reviewer_jwt': reviewer.reviewer, 'disable_local_ca_jwt': True}


class Trace:
    def __init__(self, client, reviewer, rows):
        self.client, self.reviewer, self.rows = client, reviewer, rows
        self.tokens = []

    def check(self, label, passed, **safe):
        if (not isinstance(label, str) or re.fullmatch(r'[a-z0-9_.]{1,150}', label) is None
                or any(type(v) not in (bool, int) for v in safe.values())):
            raise ValueError('unsafe_observation')
        self.rows.append({'case': PREFIX + label, 'passed': passed is True, **safe})
        if passed is not True:
            raise ScenarioFailure(PREFIX + label)

    def call(self, label, path, body=None, *, method='POST', bearer=None, expected=200,
             source='127.0.0.1', reviews=0, wrap=None, spoof=False):
        before = len(self.reviewer.calls)
        response = self.client.request(method, path, body, token=bearer, source=source,
                                       wrap_ttl=wrap, spoof=spoof)
        count = len(self.reviewer.calls) - before
        self.check(label, response.status == expected and count == reviews
                   and (reviews == 0 or self.reviewer.request_valid),
                   status=response.status, tokenreviews=count, source_family=self.client.last_family)
        return response.body

    def login(self, label, *, source='127.0.0.1', expected=200, reviews=1, wrap=None):
        result = self.call(label, BASE + '/login', {'role': 'app', 'jwt': self.reviewer.presented},
                           bearer='', source=source, expected=expected, reviews=reviews, wrap=wrap)
        auth = result.get('auth', {})
        if expected == 200:
            self.check(label + '.issued', all(isinstance(auth.get(field), str) and bool(auth[field])
                       for field in ('client_token', 'accessor', 'entity_id')) and auth.get('renewable') is True)
            self.tokens.append(auth['client_token'])
        else:
            self.check(label + '.no_publication', not auth and not result.get('wrap_info'))
        return auth

    def bounds(self, label, auth, expected):
        data = self.call(label, 'auth/token/lookup', {'token': auth['client_token']},
                         source='127.0.0.2').get('data', {})
        self.check(label + '.snapshot', data.get('bound_cidrs', []) == expected)

    def renew(self, label, auth, *, self_source='127.0.0.1'):
        for entry, body, bearer, source in [
                ('renew-self', {}, auth['client_token'], self_source),
                ('renew', {'token': auth['client_token']}, None, '127.0.0.2'),
                ('renew-accessor', {'accessor': auth['accessor']}, None, '127.0.0.2')]:
            name = label + '.' + entry.replace('-', '_')
            result = self.call(name, 'auth/token/' + entry, dict(body, increment=300), bearer=bearer, source=source)
            self.check(name + '.shape', renewal_token_shape(result.get('auth'), auth['client_token'],
                       via_accessor=entry == 'renew-accessor'))


def restart(instance, binary, key, t, label):
    instance.stop()
    instance.binary = binary
    instance.start()
    t.call(label + '.unseal', 'sys/unseal', {'key': key})


def children(t, parent, label):
    result = {}
    for kind, path in [('child', 'create'), ('orphan', 'create-orphan')]:
        auth = t.call(label + '.' + kind, 'auth/token/' + path,
                      {'policies': ['default'], 'ttl': 600}, bearer=parent['client_token']).get('auth', {})
        t.check(label + '.' + kind + '.issued', isinstance(auth.get('client_token'), str) and bool(auth['client_token']))
        t.tokens.append(auth['client_token'])
        result[kind] = auth
    return result


def scan_secrets(instance, reviewer, key, t, label):
    sensitive = [key, instance.token, reviewer.reviewer, reviewer.presented, *t.tokens]
    files = [p for p in (instance.root / 'data').rglob('*') if p.is_file()]
    files += [instance.root / 'server.log', instance.root / 'audit.jsonl']
    t.check(label, all(secret.encode() not in p.read_bytes() for p in files if p.exists() for secret in sensitive)
            and not any(secret in json.dumps(t.rows) for secret in sensitive))


def prepare_legacy(instance, reviewer, rows):
    instance.start()
    status, initialized = instance.call('POST', 'sys/init', {'secret_shares': 1, 'secret_threshold': 1})
    if status != 200:
        raise ScenarioFailure('legacy_initialization_failed')
    instance.token, key = initialized['root_token'], initialized['keys_base64'][0]
    t = Trace(SourceClient(instance.address, instance.root / 'ca.crt', instance.token), reviewer, rows)
    t.call('legacy.unseal', 'sys/unseal', {'key': key})
    t.call('legacy.kv', VALUE_PATH, {'data': {'synthetic': True}})
    policy = ('path "auth/token/create" { capabilities = ["update", "sudo"] } '
              'path "auth/token/create-orphan" { capabilities = ["update", "sudo"] }')
    t.call('legacy.policy', 'sys/policies/acl/upgrade-child', {'policy': policy}, expected=204)
    t.call('legacy.mount', 'sys/auth/kubernetes-cidr-upgrade', {'type': 'kubernetes'}, expected=204)
    t.call('legacy.config', BASE + '/config', old_configuration(reviewer, (instance.root / 'ca.crt').read_text()), expected=204)
    payload = old_role()
    t.check('legacy.no_cidr_role_field', 'token_bound_cidrs' not in payload)
    t.call('legacy.role', BASE + '/role/app', payload, expected=204)
    role_snapshot = t.call('legacy.role_read', BASE + '/role/app', method='GET').get('data', {})
    auth = t.login('legacy.login')
    t.bounds('legacy.lookup', auth, [])
    t.call('legacy.other_source', 'auth/token/lookup-self', method='GET', bearer=auth['client_token'], source='127.0.0.2')
    saved = children(t, auth, 'legacy')
    for name, child in saved.items():
        t.bounds('legacy.' + name + '.lookup', child, [])
    t.check('legacy.complete', True)
    return t, key, auth, saved, role_snapshot


def run_upgrade(instance, reviewer, candidate, legacy, rows):
    t, key, old, old_children, old_readback = prepare_legacy(instance, reviewer, rows)
    store = instance.root / 'data'
    instance.stop()
    application = durable_manifest(store, application_only=True)
    restart(instance, candidate, key, t, 'current')
    t.check('current.reopen_unchanged', durable_manifest(store, application_only=True) == application)
    before = durable_manifest(store)
    value = t.call('current.kv', VALUE_PATH, method='GET').get('data', {}).get('data')
    t.check('current.value_preserved', value == {'synthetic': True})
    role = t.call('current.role', BASE + '/role/app', method='GET').get('data', {})
    retained = {k: v for k, v in role.items() if k != 'token_bound_cidrs' or k in old_readback}
    t.check('current.old_fields_preserved', retained == old_readback and role.get('token_bound_cidrs') == [])
    for name, auth in [('direct', old), *old_children.items()]:
        t.bounds('current.old_' + name, auth, [])
        t.call('current.old_' + name + '.other_source', 'auth/token/lookup-self', method='GET',
               bearer=auth['client_token'], source='127.0.0.2')
    t.check('current.pure_reads_unchanged', durable_manifest(store) == before)
    restart(instance, candidate, key, t, 'current.second')
    t.check('current.second_reopen_unchanged', durable_manifest(store, application_only=True) == application)
    t.call('bound.role', BASE + '/role/app', {'token_bound_cidrs': ['127.0.0.1/32']}, expected=204)
    role = t.call('bound.read_role', BASE + '/role/app', method='GET').get('data', {})
    t.check('bound.canonical', role.get('token_bound_cidrs') == ['127.0.0.1'])
    direct = t.login('bound.login')
    t.bounds('bound.lookup', direct, ['127.0.0.1'])
    before = durable_manifest(store)
    t.login('bound.foreign_login', source='127.0.0.2', expected=403, reviews=0, wrap='60s')
    t.call('bound.foreign_token', 'auth/token/lookup-self', method='GET', bearer=direct['client_token'],
           source='127.0.0.2', expected=403, spoof=True)
    denied = t.call('bound.foreign_renew', 'auth/token/renew-self', {'increment': 300},
                    bearer=direct['client_token'], source='127.0.0.2', expected=403, wrap='60s')
    t.check('bound.rejections_unchanged', durable_manifest(store) == before
            and not denied.get('auth') and not denied.get('wrap_info'))
    reviewer.mode = 'unavailable'
    for name, auth in [('direct', old), *old_children.items()]:
        t.call('bound.old_' + name + '.unconstrained', 'auth/token/lookup-self', method='GET',
               bearer=auth['client_token'], source='127.0.0.2')
    t.renew('bound.old_renew', old, self_source='127.0.0.2')
    t.renew('bound.current_renew', direct)
    new_children = children(t, direct, 'bound')
    for name, auth in new_children.items():
        t.bounds('bound.' + name + '.lookup', auth, ['127.0.0.1'] if name == 'child' else [])
        t.call('bound.' + name + '.other_source', 'auth/token/lookup-self', method='GET',
               bearer=auth['client_token'], source='127.0.0.2', expected=403 if name == 'child' else 200)
    t.call('clear.role', BASE + '/role/app', {'token_bound_cidrs': []}, expected=204)
    t.bounds('clear.issued_snapshot', direct, ['127.0.0.1'])
    reviewer.mode = 'normal'
    fresh = t.login('clear.fresh_login', source='127.0.0.2')
    t.bounds('clear.fresh_lookup', fresh, [])
    restart(instance, candidate, key, t, 'reopen')
    t.bounds('reopen.snapshot', direct, ['127.0.0.1'])
    t.call('reopen.foreign_rejected', 'auth/token/lookup-self', method='GET', bearer=direct['client_token'],
           source='127.0.0.2', expected=403)
    instance.stop()
    application = durable_manifest(store, application_only=True)
    instance.binary = legacy
    instance.start()
    t.call('downgrade.unseal_rejected', 'sys/unseal', {'key': key}, expected=503)
    t.call('downgrade.remains_sealed', 'sys/health', method='GET', expected=503)
    instance.stop()
    t.check('downgrade.application_unchanged', durable_manifest(store, application_only=True) == application)
    restart(instance, candidate, key, t, 'recovery')
    t.check('recovery.application_unchanged', durable_manifest(store, application_only=True) == application)
    for name, auth in [('old', old), ('fresh', fresh), *[('old_' + k, v) for k, v in old_children.items()]]:
        t.call('recovery.' + name + '.unconstrained', 'auth/token/lookup-self', method='GET',
               bearer=auth['client_token'], source='127.0.0.2')
    t.bounds('recovery.snapshot', direct, ['127.0.0.1'])
    for name, auth in [('direct', direct), ('child', new_children['child'])]:
        t.call('recovery.' + name + '.foreign_rejected', 'auth/token/lookup-self', method='GET',
               bearer=auth['client_token'], source='127.0.0.2', expected=403)
    t.call('recovery.orphan_unconstrained', 'auth/token/lookup-self', method='GET',
           bearer=new_children['orphan']['client_token'], source='127.0.0.2')
    reviewer.mode = 'unavailable'
    t.renew('recovery.renew', direct)
    instance.stop()
    scan_secrets(instance, reviewer, key, t, 'plaintext_credentials_absent')
    t.check('complete', True)


def required_cases(prepare):
    names = {'legacy.no_cidr_role_field', 'legacy.login.issued', 'legacy.lookup.snapshot',
             'legacy.child.lookup.snapshot', 'legacy.orphan.lookup.snapshot', 'legacy.complete'}
    if prepare:
        names.add('legacy.plaintext_credentials_absent')
    else:
        names |= {'current.reopen_unchanged', 'current.old_fields_preserved', 'current.pure_reads_unchanged',
                  'current.second_reopen_unchanged', 'bound.canonical', 'bound.lookup.snapshot',
                  'bound.foreign_login.no_publication', 'bound.rejections_unchanged',
                  'bound.old_direct.unconstrained', 'bound.child.other_source', 'bound.orphan.other_source',
                  'clear.issued_snapshot.snapshot', 'clear.fresh_lookup.snapshot', 'reopen.foreign_rejected',
                  'downgrade.unseal_rejected', 'downgrade.application_unchanged', 'recovery.application_unchanged',
                  'recovery.snapshot.snapshot', 'recovery.direct.foreign_rejected', 'recovery.child.foreign_rejected',
                  'recovery.orphan_unconstrained', 'plaintext_credentials_absent', 'complete'}
        names |= {phase + '.' + entry + '.shape' for phase in ['bound.old_renew', 'bound.current_renew', 'recovery.renew']
                  for entry in ['renew_self', 'renew', 'renew_accessor']}
    return {PREFIX + name for name in names}


def complete(rows, prepare):
    if not isinstance(rows, list) or not rows:
        return False
    names = []
    for row in rows:
        if (not isinstance(row, dict) or not isinstance(row.get('case'), str)
                or re.fullmatch(re.escape(PREFIX) + r'[a-z0-9_.]{1,150}', row['case']) is None
                or row.get('passed') is not True
                or any(type(v) not in (bool, int) for k, v in row.items() if k not in ('case', 'passed'))):
            return False
        names.append(row['case'])
    return len(names) == len(set(names)) and required_cases(prepare).issubset(names)


def main():
    parser = SafeArgumentParser(description=__doc__)
    parser.add_argument('--binary', type=Path)
    parser.add_argument('--prepare-legacy', action='store_true')
    for name in ('legacy-binary', 'expected-legacy-sha256', 'build-source-commit', 'output'):
        parser.add_argument('--' + name, required=True)
    args = parser.parse_args()
    if re.fullmatch(r'[0-9a-f]{40}', args.build_source_commit) is None:
        parser.error('full build source commit required')
    if LEGACY_RECEIPT is None:
        parser.error('legacy schema30 receipt is not yet pinned')
    legacy = Path(args.legacy_binary).resolve(strict=True)
    admit_legacy_receipt(args.expected_legacy_sha256, json.loads(LEGACY_RECEIPT.read_text()))
    if args.prepare_legacy:
        if args.binary is not None or args.build_source_commit != LEGACY_SOURCE or file_hash(legacy) != LEGACY_SHA256:
            parser.error('prepare requires only the exact pinned historical binary/source')
        candidate = legacy
        candidate_hash = legacy_hash = LEGACY_SHA256
    else:
        if args.binary is None:
            parser.error('candidate binary required')
        candidate = args.binary.resolve(strict=True)
        candidate_hash, legacy_hash = validate_binary_pins(candidate, legacy, args.expected_legacy_sha256)
    output = Path(args.output).absolute()
    admitted = admit_output(output)
    before, runner_hash = source_identity(ROOT, candidate), file_hash(Path(__file__))
    root = Path(tempfile.mkdtemp(prefix='heptabao-kubernetes-cidrs-upgrade-'))
    root.chmod(0o700)
    instance = reviewer = None
    rows, failure = [], None
    try:
        instance = Instance(legacy, root / 'candidate')
        settings = json.loads((instance.root / 'server.json').read_text())
        settings.update(lifecycle_interval_seconds=0, outbound_endpoints=[])
        private_write(instance.root / 'server.json', settings)
        reviewer = Reviewer(instance.root / 'tls.crt', instance.root / 'tls.key', 'candidate')
        private, jwk = signing_key('ES256', 'synthetic-kubernetes-cidr-upgrade')
        reviewer.presented = assertion(private, jwk)
        if args.prepare_legacy:
            t, key, *_ = prepare_legacy(instance, reviewer, rows)
            instance.stop()
            scan_secrets(instance, reviewer, key, t, 'legacy.plaintext_credentials_absent')
        else:
            run_upgrade(instance, reviewer, candidate, legacy, rows)
    except Exception as error:
        failure = next((row['case'] for row in reversed(rows) if row['passed'] is not True),
                       'fixture_' + type(error).__name__)
    finally:
        if instance is not None:
            instance.stop()
        if reviewer is not None:
            reviewer.close()
        shutil.rmtree(root)
    after = source_identity(ROOT, candidate)
    binaries_unchanged = after['binary_sha256'] == candidate_hash and file_hash(legacy) == legacy_hash
    source_unchanged, runner_unchanged = before == after, file_hash(Path(__file__)) == runner_hash
    if not binaries_unchanged or not source_unchanged or not runner_unchanged:
        failure = 'source_binary_or_runner_changed'
    if not complete(rows, args.prepare_legacy):
        failure = failure or 'incomplete_observations'
    report = {'schema': 'heptabao.kubernetes-cidrs-upgrade.v1', 'status': 'passed' if failure is None else 'failed',
              'from_schema': 30, 'minimum_to_schema': None if args.prepare_legacy else 31,
              'prepare_legacy_only': args.prepare_legacy, 'failure': failure, 'cases': rows,
              'source_identity': before, 'source_and_binary_unchanged': source_unchanged,
              'legacy_source_commit': LEGACY_SOURCE, 'legacy_harness_commit': LEGACY_HARNESS,
              'legacy_binary_sha256': legacy_hash, 'legacy_receipt_sha256': file_hash(LEGACY_RECEIPT),
              'candidate_binary_sha256': None if args.prepare_legacy else candidate_hash,
              'build_source_commit': args.build_source_commit,
              'build_source_binding_basis': 'caller-supplied build commit and observed binary hash, not independent attestation',
              'binaries_unchanged': binaries_unchanged, 'runner_sha256': runner_hash, 'runner_unchanged': runner_unchanged,
              'candidate_startup_enrollment_empty': True, 'reopen_replay_ledger_may_change': True,
              'application_artifact_scope': 'all store entries except root ledger.hbl, rebuilt before schema validation',
              'synthetic_only': True, 'actual_https_tokenreview': True, 'actual_kube_apiserver': False,
              'rolling_upgrade_qualification': False, 'full_migration_qualification': False,
              'independent_qualification': False, 'production_authority': False}
    if admit_output(output) != admitted:
        raise ValueError('report_parent_changed')
    private_write(output, report, replace=False)
    print(json.dumps({'status': report['status'], 'checks': len(rows), 'failure': failure}))
    return 0 if failure is None else 1


if __name__ == '__main__':
    raise SystemExit(main())
